<a href="https://colab.research.google.com/github/MaxiSancari/mis-programas-python/blob/master/Jugadores_Buenardos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import torch
import pandas as pd

# Trabajando con tensores

---



In [2]:
torch.__version__

'1.5.1+cu101'

In [3]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [6]:
tensor_b = torch.Tensor (2,2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[7.5759e-36, 0.0000e+00],
        [1.5414e-43, 1.6115e-43]])


tensor([[0.1976, 0.0739],
        [0.7977, 0.1367]])

In [7]:
tensor_c = torch.rand (2,2)
tensor_c

tensor([[0.5456, 0.5952],
        [0.5186, 0.7446]])

In [8]:
result = tensor_b + tensor_c
result

tensor([[0.7432, 0.6692],
        [1.3164, 0.8814]])

In [9]:
result.shape
reshaped = result.view(4,1)
reshaped

tensor([[0.7432],
        [0.6692],
        [1.3164],
        [0.8814]])

In [13]:
points = torch.tensor ([[1.0, 2.0],[3.0, 4.0]])
print(points)
points[0][1] = 2.5
print(points)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


In [17]:
p_t = points.t()
print(p_t)
p_t, p_t.stride()


tensor([[1.0000, 3.0000],
        [2.5000, 4.0000]])


(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

In [23]:
tensor_x = torch.tensor([1,2,3,4])
tensor_x, torch.unsqueeze(tensor_x, 1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [24]:
import numpy as np

In [26]:
numpyArray = np.random.rand(2,2)

from_numpy = torch.from_numpy(numpyArray)
from_numpy 

tensor([[0.9494, 0.8862],
        [0.8043, 0.5123]], dtype=torch.float64)

# Representar datos con tensores

---



In [28]:
print(from_numpy)
torch.mean(from_numpy)
torch.mean(from_numpy, dim=0)
torch.mean(from_numpy, dim=1)

tensor([[0.9494, 0.8862],
        [0.8043, 0.5123]], dtype=torch.float64)


tensor([0.9178, 0.6583], dtype=torch.float64)

In [29]:
#std desviacion estandar
torch.std(from_numpy, dim=1)

tensor([0.0447, 0.2065], dtype=torch.float64)

In [38]:
torch.save (from_numpy, 'tensor.t')

In [40]:
load = torch.load ('tensor.t')
load

tensor([[0.9494, 0.8862],
        [0.8043, 0.5123]], dtype=torch.float64)

In [42]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [43]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [49]:
#dropna eliminar en las filas cuando cualquiera es nulo
subset = dataframe[['Overall', 'Age','International Reputation', 'Weak Foot',
       'Skill Moves']].dropna (axis=0, how ='any')
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [ ]:
data = players[:, 1:]
data, data.shape

In [51]:
#tenes unicamente la 1er columna
target = players[:,0]
target, target.shape


(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [52]:
#media mean
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [53]:
#std desviacion estandar
std = torch.std(data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [54]:
# normalizar datos data - media dividido por el cuadrado(sqrt) std
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [62]:
#separar a los jugadores en bueno,maso,malo [torch.ge = mayor o igual] [torch.gt = mas que] [torch.lt = menos que] [torch.le = menor o igual]
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
notSoGood = data[torch.le(target, 70)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
notSoGoodMean = torch.mean(notSoGood, dim=0)

#goodMean, averageMean, notSoGoodMean
#zip para agrupar los argumentos y  numerate permite iterar un indice y los argumentos [:25 = la 1ra columna tiene un texto muy largo] [:6 2f = nro flotanto que tiene hasta 2 digitos en su parte fraccionaria ] 
for i, args in enumerate(zip(columns, goodMean,averageMean,notSoGoodMean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
